### ISSUE TITLE
[raspberrypi-docker-monitor] No CPU usage stats

### ISSUE THREAD

**Issue by BenSeventy9** [pi-hosted/pi-hosted#142]
Am I the only one who has this issue?<br><br><br>

![Docker and OS Metrics for Raspberry Pi 15120 - Dashboards - Grafana](https://user-images.githubusercontent.com/52075695/215331711-0ee02c0c-2b68-4c31-a060-3bab0f8418b1.png)

I found out that editing CPU Usage changing from this
```
100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle",job="$job"}[$interval])) * 100)
```
to this works
```
100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[$interval])) * 100)
```

![Screenshot 2023-01-29 at 15-12-49 Edit panel - Docker and OS Metrics for Raspberry Pi 15120 - Dashboards - Grafana](https://user-images.githubusercontent.com/52075695/215332229-ed9fab33-6c70-4b58-b728-1b590a8f2376.png)

**Comment by Macleykun** [comment]
Just curious, but what you have set as the variable for job?
![image](https://user-images.githubusercontent.com/26381427/216711938-229cf259-fa7b-4fb5-82e7-4cd11e9b062f.png)
you can find this when clicking here:
![image](https://user-images.githubusercontent.com/26381427/216711975-29e6e848-5902-46da-a776-0f6d4bf8acbc.png)

I assume you tried removing the dashboard and re-adding it? (and that you followed the steps here: https://github.com/pi-hosted/pi-hosted/blob/master/docs/rpi_docker_monitor.md ?

It's kinda strange, but when i imported it, i don't seem to have that issue:
![image](https://user-images.githubusercontent.com/26381427/216712375-9709086d-0cc2-4743-98b9-22d314bc6441.png)

I did use this one: https://github.com/pi-hosted/pi-hosted/blob/master/configs/rpi_dashboard/arm_rpi_dashboard.json as i have an arm device (not amd).

**Comment by blenherr** [comment]
Thanks for the answer.

> Just curious, but what you have set as the variable for job?

![Screenshot 2023-02-03 at 23-30-54 Variables - Docker and OS Metrics for Raspberry Pi 15120 - Dashboards - Grafana](https://user-images.githubusercontent.com/122442255/216725739-dd7d1121-b78e-4260-8dba-275af8d3a4ba.png)

> I assume you tried removing the dashboard and re-adding it? (and that you followed the steps here: https://github.com/pi-hosted/pi-hosted/blob/master/docs/rpi_docker_monitor.md ?

I followed the steps and i did all that several times in the past years. Removing the dashboard and re-adding it does not make a difference.

> I did use this one: https://github.com/pi-hosted/pi-hosted/blob/master/configs/rpi_dashboard/arm_rpi_dashboard.json as i have an arm device (not amd).

Yes I use that json too.

> It's kinda strange

indeed!

I have to mention that I have this regardless of the system (RPi3b+ and ZeroW), but only on newly installed systems.
It's fine on a system that's about 3-4 months old.

**Comment by BenSeventy9** [comment]
Thanks for the answer.

> Just curious, but what you have set as the variable for job?

![Variables - Docker and OS Metrics for Raspberry Pi 15120 - Dashboards - Grafana](https://user-images.githubusercontent.com/52075695/216726590-17812d0a-639b-49ca-9bab-5e9b672c4437.png)

> I assume you tried removing the dashboard and re-adding it? (and that you followed the steps here: https://github.com/pi-hosted/pi-hosted/blob/master/docs/rpi_docker_monitor.md ?

I followed the steps and i did all that several times in the past years. Removing the dashboard and re-adding it does not make a difference.

> It's kinda strange

Indeed

I have to mention that I have this regardless of the system (RPi3b+ and ZeroW), but only on newly installed systems.
It's fine on a system that's about 3-4 months old.

**Comment by BenSeventy9** [comment]
I tried adding "prometheus" seperatly but does allso not work.
```
100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle",job="prometheus"}[$interval])) * 100)
```

**Comment by henkiewie** [comment]
I found the same thing. I made a remark about it in the pi-hosted discord server a couple of days ago. I also found that @oijkn made some new revisions of the dashboard. So I tried the latest one (rev10) 15120.  CPU usage seems to be working again. But then this one had no RootFS and disk info 😞 . When you take a look at the original node-exporter image it uses `/:/host,ro` as a volume. It has no volume in the template. So when I added that to the node exporter container image, I got the info I wanted, but had to change the queries from `100 - ((node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"})`.
to 
`100 - ((node_filesystem_avail_bytes{mountpoint="/host",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{mountpoint="/host",fstype!="rootfs"})`
😄 
It seems like the original does not support host disk info because it was not ment to run in a container?, but it can now easily be added by changing all relation from / (5) in the queries /host. It's working for me.
For example `Rootfs used`
<img width="267" alt="Screenshot 2023-02-07 at 07 04 45" src="https://user-images.githubusercontent.com/74558874/217161851-eee0f41b-c55e-46c1-b3d9-83e2aaabdd21.png">
<img width="267" alt="Screenshot 2023-02-07 at 07 11 07" src="https://user-images.githubusercontent.com/74558874/217162849-7f06995c-d6f9-4c8e-8f22-0c9648b7d4f6.png">
So it looks like this now.
<img width="1969" alt="Screenshot 2023-02-07 at 06 57 30" src="https://user-images.githubusercontent.com/74558874/217160743-10f10353-6853-49f2-b3d8-3f80f0ad649b.png">
For now I also wanted to see the number of containers instead of cores that never change (i hope 😄 ) anyway, so I copied that from the old one.
<img width="1967" alt="Screenshot 2023-02-07 at 07 20 35" src="https://user-images.githubusercontent.com/74558874/217164357-f793e0c2-0443-4b4e-abdd-4b67d8fd74c1.png">

Maybe I will make a PR and ask to implement my changes.
