### ISSUE TITLE
[QUESTION] Installing tiddlywiki:  Getting error creating directory '/var/lib/tiddlywiki/mywiki'

### ISSUE THREAD

**Issue by al-jimenez** [pi-hosted/pi-hosted#50]
**Question**
I used Portainer to install Homer and it worked great.   I then tried "tiddlywiki", which I have used many years ago.   But the container said it installed correctly but is not available.    (Used your latest 2022-07-31 portatiner template)

When I checked the log in portainer it said "Error creating directory '/var/lib/tiddlywiki/mywiki'".    

My question is did I set up the docker container incorrectly?   Any help would be appreciated.

**Context**
I am running containers / Portainer on Raspberry Pi 4 4GB with updated/upgraded Raspi OS on an SSD.   

The installation of the  "tiddlywiki" successfully creates the path "/portainer/Files/AppData/Config/TiddlyWiki" and it starts the container shows correct port configs but after a while port configs go away; and container log shows:  Error: Error creating directory '/var/lib/tiddlywiki/mywiki'

Any direction you can provide would be appreciated.    

I very much appreciate your videos and the progressive topics with RASPI that you cover in them.   Keep up the good work!

**Comment by Macleykun** [comment]
This is because of this:

https://hub.docker.com/r/nicolaw/tiddlywiki/#:~:text=Specifying%20a%20volume%20bind%20mount%20location%20for%20/var/lib/tiddlywiki%20will%20cause%20the%20Tiddler%20data%20to%20be%20written%20to%20that%20location%20on%20your%20local%20filesystem.

It can't create the files that are overwritten because it's not owner of the just added volume/bind.

You could copy the content from within the docker container: /var/lib/tiddlywiki to your local machine, create a user named node and make that full owner of the folder recursively.

This can also be done by pi-hosted with a pre-run script. But we do need a online location to store the content of that folder so others can begin the wizard.

**Comment by Macleykun** [comment]
@al-jimenez found out why more exactly
Please run:
```
sudo chown 1000:1000 /portainer/Files/AppData/Config/TiddlyWiki/
```
That'll fix it for ya :) will add this to the "pre-install" part. I don't believe we should need a script as it's a one-liner.
